web:
  build: ./opencart_local
  ports:
    - "14001:80"
  links:
    - db
  env_file:
    - env
  restart: always

db:
  image: mysql:5.6
  ports:
    - "14002:3306"
  env_file:
    - env
  restart: always

